[package]
name = "ecsast"
version = "0.1.0"
edition = "2024"

[dependencies]
bumpalo = "3"
cranelift-codegen = "0.116"
cranelift-frontend = "0.116"
cranelift-module = "0.116"
cranelift-object = "0.116"
target-lexicon = "0.13"
